project_name: test-release
builds:
  - main: .
    binary: test-release
    dir: ./cmd/test-release
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows


archives:
    - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
      format: tar.xz
      format_overrides:
        - goos: windows
          format: zip
      replacements:
          darwin: macOS
      wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
release:
  draft: true  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
